"""made event owner_id non unique to allow multiple owned events

Revision ID: 1fd2523582ac
Revises: bcf9c2bdf42a
Create Date: 2023-08-19 13:21:26.447430

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fd2523582ac'
down_revision: Union[str, None] = 'bcf9c2bdf42a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
