"""added separate keys for inviter and invitee

Revision ID: a4189e9b553f
Revises: a0469fd0b337
Create Date: 2023-08-18 12:08:13.503234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a4189e9b553f'
down_revision: Union[str, None] = 'a0469fd0b337'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sender_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('invitee_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_invite_user_id_user', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_invite_sender_id_user'), 'user', ['sender_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('fk_invite_invitee_id_user'), 'user', ['invitee_id'], ['id'])
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invite', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_invite_invitee_id_user'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('fk_invite_sender_id_user'), type_='foreignkey')
        batch_op.create_foreign_key('fk_invite_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.drop_column('invitee_id')
        batch_op.drop_column('sender_id')

    # ### end Alembic commands ###
