"""re-added foreign_keys param from event.owner

Revision ID: c1063fd36012
Revises: 52d463f1d00b
Create Date: 2023-08-16 20:12:14.998042

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1063fd36012'
down_revision: Union[str, None] = '52d463f1d00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
