"""removed User column with foreign key pointing to an event

Revision ID: d7d167dc5927
Revises: c1063fd36012
Create Date: 2023-08-17 09:52:35.752598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7d167dc5927'
down_revision: Union[str, None] = 'c1063fd36012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint('fk_user_my_event_id_event', type_='foreignkey')
        batch_op.drop_column('my_event_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_event_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key('fk_user_my_event_id_event', 'event', ['my_event_id'], ['id'])

    # ### end Alembic commands ###
