"""updated owned/owner relationships to correctly reflect owners of events

Revision ID: e83460e16980
Revises: 55af29dd81f1
Create Date: 2023-08-16 19:40:40.838207

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e83460e16980'
down_revision: Union[str, None] = '55af29dd81f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_event_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('fk_user_my_event_event', type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('fk_user_my_event_id_event'), 'event', ['my_event_id'], ['id'])
        batch_op.drop_column('my_event')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('my_event', sa.INTEGER(), nullable=True))
        batch_op.drop_constraint(batch_op.f('fk_user_my_event_id_event'), type_='foreignkey')
        batch_op.create_foreign_key('fk_user_my_event_event', 'event', ['my_event'], ['id'])
        batch_op.drop_column('my_event_id')

    # ### end Alembic commands ###
