"""added owner key to Event model

Revision ID: fd4da35eee6e
Revises: 29a2ca147f69
Create Date: 2023-08-16 09:00:29.842678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd4da35eee6e'
down_revision: Union[str, None] = '29a2ca147f69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('owner', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_event_owner_user'), 'event', 'user', ['owner'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_event_owner_user'), 'event', type_='foreignkey')
    op.drop_column('event', 'owner')
    # ### end Alembic commands ###
